dist: xenial
sudo: required

language: elixir
elixir:
- 1.8.1
otp_release:
- 21.3

env:
  global:
    - HEX_HTTP_CONCURRENCY=1
    - HEX_HTTP_TIMEOUT=120

before_install:
- sudo sysctl net.ipv6.conf.all.disable_ipv6=1
- sudo sysctl net.ipv6.conf.default.disable_ipv6=1
- sudo sysctl net.ipv6.conf.lo.disable_ipv6=1
- sudo service docker restart

install:
- mix local.rebar --force
- mix local.hex --force
- mix deps.get

script:
- docker --version
- docker build --file Dockerfile .

notifications:
  email:
    - gergo.papp-szentannai@ni.com
